{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iabhishekmp.flutter_mod",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6150291,
          "sha512": "70fba0e9395e535b4f54d807bc28a759b9d73bfeedcd53312bef9962ec3cbf8525096c401779eb1748eff9f0b1ff899ab20c7e180decdd7d17e7693e1c556c8c",
          "sha256": "1bc1cc9a47419abf784c491e578ffcdad5112c6f8c61e3a2d8254a8e71286ee3",
          "sha1": "12a47f1159866b3f6fd9c9a3013c6089660e0ec8",
          "md5": "38e7bb5622315c01384c3fe864bb0411"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 6150291,
          "sha512": "70fba0e9395e535b4f54d807bc28a759b9d73bfeedcd53312bef9962ec3cbf8525096c401779eb1748eff9f0b1ff899ab20c7e180decdd7d17e7693e1c556c8c",
          "sha256": "1bc1cc9a47419abf784c491e578ffcdad5112c6f8c61e3a2d8254a8e71286ee3",
          "sha1": "12a47f1159866b3f6fd9c9a3013c6089660e0ec8",
          "md5": "38e7bb5622315c01384c3fe864bb0411"
        }
      ]
    }
  ]
}
