{
  "formatVersion": "1.1",
  "component": {
    "group": "com.iabhishekmp.flutter_mod",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3866745,
          "sha512": "d2bac8570e67b5a86f6f21f434a079b357f23b6549ad29ac6b61540357eabb7c75ae75a179abce4ad96194ebb7deb96b6c4bd14eda128b51464a4644586f62ac",
          "sha256": "d7fb6ada8dbf2340ffbaf871346d3721dd61f3bb732509df476f09c2b38fa369",
          "sha1": "fc9bd40c0101e771151bef109bfc8e4bfdd25c74",
          "md5": "d101861463d5c07ee33735b3e9f7bc12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-1a65d409c7a1438a34d21b60bf30a6fd5db59314"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 3866745,
          "sha512": "d2bac8570e67b5a86f6f21f434a079b357f23b6549ad29ac6b61540357eabb7c75ae75a179abce4ad96194ebb7deb96b6c4bd14eda128b51464a4644586f62ac",
          "sha256": "d7fb6ada8dbf2340ffbaf871346d3721dd61f3bb732509df476f09c2b38fa369",
          "sha1": "fc9bd40c0101e771151bef109bfc8e4bfdd25c74",
          "md5": "d101861463d5c07ee33735b3e9f7bc12"
        }
      ]
    }
  ]
}
